### ISSUE TITLE
Continue the line after drawing it

### ISSUE THREAD

**Issue by Patabugen** [Igor-Vladyka/leaflet.motion#16] opened 2020-11-12 15:33 UTC
I'm displaying routes that someone has traveled, your (superb) plugin lets me draw the line in a more natural way.

However I also want to display routes in real-time, which means loading the saved route and drawing it with leaflet.motion, but then adding to the length one or two waypoints at a time.

Do you have any suggestions for how I can add to an existing line (which may still be in motion, or may have finished?).

I've been experimenting with the addLatlng but don't think that's the right thing to do. I've also pondered using your Group feature and adding a new motionLine each time - but will be adding hundreds of mini lines that way and thought I'd see if there was a way to add one at a time?

**Comment by Igor-Vladyka** [comment] 2020-11-17 10:28
Hello there.

I may need to think about it for a bit. It's not straight forward for now.

**Comment by luquezsantiago86** [comment] 2021-02-09 11:22
Hello, I have an interest in this. 

Do you have any idea on how to do it?

For the moment what I am doing is to create an interval to read the last 2 coordinates os the polyline (the previous coordinate and the new added cordinate),  and inside this interval I have the `var lastLine = L.motion.polyline(...)`.

I works, but the problem is that the interval keeps drawing the same coordinates until I have a new coordinate.

![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/60870542/107356512-cff6e600-6ac8-11eb-94a6-c295c87ea2a1.gif)


Also, I was looking to hide the marker and I couldnt, I thought it was the "showMarker" option that  controls that feature.

**Comment by Patabugen** [comment] 2021-02-17 16:54
I've not worked on this since, but hopefully will be in the next month or two so will let you know if I manage anything.

The objects are just JavaScript objects - could you add a property to them to record whether you've drawn the or not and skip the interval if so?

I'd be interested to see your code if it's somewhere you can share it.

**Comment by Igor-Vladyka** [comment] 2021-02-18 08:47
Hello guys,

Have you tried to use Seq object? Create a seq with a initial line (when creating a line you surelly know start point and end point) And then just add to the seq new\next lines.

**Comment by luquezsantiago86** [comment] 2021-02-18 09:32
No, but it seems very usefull, it is a library? I will investigate about it. Thanks!

**Comment by luquezsantiago86** [comment] 2021-02-18 10:04
@Patabugen here is the section of my code where I tried to use motion with realtime feature, but I get a problem with the zoom.

https://github.com/luquezsantiago86/motion_rt/

Let me know if you if I can help you with something, and if you have any idea about this.

**Comment by luquezsantiago86** [comment] 2021-02-28 19:07
> Hello guys,
> 
> Have you tried to use Seq object? Create a seq with a initial line (when creating a line you surelly know start point and end point) And then just add to the seq new\next lines.

Hi @Igor-Vladyka sorry to bother you. I came back to investigate this again. Do you have more information of what you said about "Seq objet"? I was look on the web but I am quite new in JS and couldnt find out what you tried to said.

Any information or example would be great, Thanks!

**Comment by Igor-Vladyka** [comment] 2021-03-08 09:33
Hello.

What I mean is
```
L.motion.seq([], options).addTo(map);
```
it's a build in structure in current library to support sequential animation objects.

**Comment by luquezsantiago86** [comment] 2021-03-08 12:37
@Igor-Vladyka Thanks so much! I will give it a try!

**Comment by Igor-Vladyka** [comment] 2022-02-05 15:07
Hey guys, I'm back.

Let me check what the hell, fix will be released in next major version soon.

**Comment by Patabugen** [comment] 2022-02-11 17:13
Welcome back @Igor-Vladyka! I'll have a look at your other comments when I'm working on that project work over the next few weeks, excited to have your input again :)

**Comment by Igor-Vladyka** [comment] 2022-02-16 12:58
Hey guys. Currently it's implemented in latest version. Please check out documentation and example [here](https://igor-vladyka.github.io/leaflet.motion/examples/sequence-add-layer-example.html), created by @Patabugen

**Closed by Igor-Vladyka** 2022-02-16 12:58 UTC
Labels: bug, enhancement
